### ISSUE TITLE
test data download

### ISSUE THREAD

**Issue by Cyril27** [lsb-riken/CUBIC-informatics#17]
Hi, I get a warning message when I try to download the .tar.bz2 test_data file telling me that the file might be damaged.
It is indeed the case, all the folders containing the images seem empty.

Would anyone have an idea on how to correctly download the test_data, or even an other set of data to use the code with ?

**Comment by s-horiguchi** [comment]
Hi @Cyril27 ,
I confirmed that I can still download the correct data from
http://cubic-atlas.riken.jp/pipeline/test_data.tar.bz2
It may be a problem with your internet connection or security software. If the file you download is always corrupted, please try from another computer.

Just in case, here is the SHA256 hash of the test_data.tar.bz2
3dadc99cb39fecea470ca5b2261a80259330a2f93ac6a597a48fe7f39b162190

Hope this helps!

**Comment by Cyril27** [comment]
Hi, thank you for your answer.
I managed to download the parameters files and 100 images from the RV registration.

Does the data also provide images from the FW registration so the MergeBrain.py script can be used after applying the HDoG_gpu.py on both set of images ?

**Comment by s-horiguchi** [comment]
Good!

About the FW images, we don't provide them now. But MergeBrain.py should work without FW images.
(Since I am working on different projects now, I am not sure about the details.)
